baseurl: "https://cafedevopslyon/"
title: "Café DevOps Lyon"
canonifyurls: true

# Voir si on utilise GoogleAnalytics
# GoogleAnalytics: ""
#
# privacy:
#   googleAnalytics:
#     anonymizeIP: true
#     respectDoNotTrack: true
#     useSessionStorage: true

params:
  # Meetup info
  Name: "Café DevOps Lyon"
  Year: "2019"
  Description: "Café DevOps Lyon"
  City:  "Lyon"
  State: "France"
  Twitter: "https://twitter.com/CafeDevOpsLyon"
  Email: "cafedevopslyon@gmail.com"

  Credits:
    - name: "Lyon Tech Hub"
      url: "http://www.lyontechhub.org/#!/"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
#    - icons
    - about
    - speakers
#    - billeterie
#    - location
#    - schedule
#    - sponsors
#    - partners
#    - contact

  # Titles which you can translate to other languages
  Titles:
    about: "À propos"
    speakers: "L'équipe"



  # About
  About:
    - title: "Café DevOps Lyon"
      img: "img/Cafe_DevOps-Coul_L.png"
      alt: "Image représentant le logo Café Devops"
      imgInRightSide: true
      text:
        - paragraph: "Bienvenue au Cafe DevOps Lyon"
        - paragraph: "Des discussions très intéressantes commencent à voir le jour sur Lyon autour la mise en production de développements, la gestion des pannes, les outils d’automatisation, les archi cloud natives et la culture qu’il faut avoir pour aller vers un mode DevOps sur une archi scalable.
Si vous êtes intéressés par ces sujets, alors abonnez vous au Meetup Café DevOps Lyon
et au compte twitter @CafeDevOpsLyon
Si vous voulez participer à l’organisation du meetup ou proposer une session, faites un mail à cafedevopslyon@gmail.com
"

    # Ici exemple pour faire des paragraphes
    # - title: ""
    #   img: "img/"
    #   text:
    #     - paragraph: ""


  # l'équipe
  Speakers:
    - name: "Daniel Gonçalves"
      description: "Co-organisateur du meetup"
      img: "img/daniel_goncalves.jpg"
      alt: "Photo d'un co-organisateur"
    - name: "Victor Gallet"
      description: "Co-organisateur du meetup, Co-organisateur du meetup AlpeCraft"
      img: "img/victor_gallet.jpg"
      alt: "Photo d'un co-organisateur"
    - name: "Franck  Depierre"
      description: "Co-organisateur du meetup"
      img: "img/franck_depierre.jpg"
      alt: "Photo d'un co-organisateur"
    - name: "Benjamin Dahon"
      description: "Co-organisateur du meetup"
      img: "img/benjamin_dahon.jpg"
      alt: "Photo d'un co-organisateur"
    - name: "Raphaël Ruelle"
      description: "Co-organisateur du meetup"
      img: "img/raphael_ruelle.jpg"
      alt: "Photo d'un co-organisateur"
    - name: "Guillaume Lacoste"
      description: "Co-organisateur du meetup"
      img: "img/guillaume_lacoste.jpg"
      alt: "Photo d'un co-organisateur"
    - name: "Cédric Vanet"
      description: "Co-organisateur du meetup"
      img: "img/cedric_vanet.jpg"
      alt: "Photo d'un co-organisateur"
    - name: "Quentin Le Baron"
      description: "Co-organisateur du meetup"
      img: "img/quentin_le_baron.png"
      alt: "Photo d'un co-organisateur"
